### ISSUE TITLE
Add extension to Eclipse Open VSX Registry

### ISSUE THREAD

**Issue by FrostmonsterSP** [k4li-0x0/cpp-class-generator#20]
Hi!

Many people use the forks of VSCode (VSCodium, as example), which shows extensions from the "Open VSX Registry" (https://open-vsx.org/) but not from the official marketplace. It's inconvenient to install extensions from the official VSCode registry because you have to either download them or apply patches.

It's not necessary. It's just a note. But it would be handy if the extension appeared in open-vsx.

Thanks!

**Comment by k4li-0x0** [comment]
I added the extension to the open-vsx repository 
[link](https://open-vsx.org/extension/k4li/cpp-class-generator)
